FROM postgres:latest

# Copy the initialization script to the container
COPY ./init.sql /docker-entrypoint-initdb.d/

# Additional configuration if needed
# COPY ./path/to/custom.conf /etc/postgresql/postgresql.conf